image: docker:latest

stages:
  - build

build-job:
  stage: build
  script:
    - echo "Build"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/devops/ubuntu-ssh --build-arg SSH_PRIVATE_KEY=${SSH_PRIVATE_KEY} .
    - docker push $CI_REGISTRY/devops/ubuntu-ssh
