image: docker:latest

stage:
  - build

build-job:
  stage: build
  script:
    - echo "Build"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/devops/ubuntu-ssh .
    - docker push $CI_REGISTRY/devops/ubuntu-ssh
